import type { Contact } from '$lib/types';

export function resetContact(): Contact {
  return {
    budget: 0,
    color: '',
    comContact: '',
    contactStage: 'Etapa1',
    contactType: '',
    contMode: '',
    createdAt: Date.now(),
    email: '',
    halfBathroom: 0,
    id: '',
    isActive: false,
    lastContact: undefined,
    lastname: '',
    lastResponse: undefined,
    locaProperty: [],
    modePay: '',
    name: '',
    notes: '',
    numBaths: 0,
    numBeds: 0,
    numParks: 0,
    propCont: '',
    publicUrl: '',
    rangeProp: '',
    selecMC: '',
    selecTO: '',
    selecTP: '',
    sendedProperties: [],
    tagsProperty: [],
    telephon: '',
    title: '',
    typeContact: '',
    typeOperation: '',
    typeProperty: '',
  };
}